spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokjha/cloudconfigsrv
          default-label: master 
  application:
    name: CONFIG_SERVER
server:
  port: 9888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost     
#file:///c:/Users/madsouza/Desktop/blogPost/config-files 